  version: '3'
    
  services:
    db:
      #image: postgres
      container_name: db
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      volumes:
        - ./postgres-data:/var/lib/postgresql/data
      build:
        context: .
        dockerfile: ./devops/db/Dockerfile.db
    web:
      build: .
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/code
      ports:
        - "8000:8000"
      depends_on:
        - db
