# Generated by Django 3.1.1 on 2020-10-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='substance',
            field=models.TextField(default='woda'),
        ),
    ]
