# Generated by Django 3.1.1 on 2020-11-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201018_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='substance',
            field=models.TextField(default='DUPA'),
        ),
    ]
