# Generated by Django 3.1.1 on 2020-11-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_mymodel_substance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodel',
            old_name='substance',
            new_name='fig1',
        ),
        migrations.AddField(
            model_name='mymodel',
            name='fig2',
            field=models.TextField(default='my_figure2'),
        ),
    ]
